apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: gcr.io/PROJECT_ID/todoimg:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp
spec:
  type: LoadBalancer
  selector:
    app: todoapp
  ports:
  - port: 80
    targetPort: 8080
